export const extraVerbs = [
  {
    id: "see",
    word: "SEE",
    korean: "보이다 · 만나다 · 이해하다",
    image: "의도하지 않아도 시야나 이해 안으로 들어옴",
    summary: "눈에 보이는 것뿐 아니라 사람을 만나고, 상황과 의미를 이해할 때도 폭넓게 씁니다.",
    forms: "see / sees · saw · seen",
    accent: "#8ec9ff",
    tint: "#eaf6ff",
    patterns: [
      { frame: "see + object", meaning: "보다·만나다", example: "I saw her yesterday.", ko: "어제 그 사람을 봤어." },
      { frame: "see + clause", meaning: "이해하다·알아보다", example: "I see why you're concerned.", ko: "왜 걱정하는지 알겠어요." },
      { frame: "see + object + verb", meaning: "~하는 것을 보다", example: "I saw him leave.", ko: "그가 나가는 걸 봤어." },
    ],
    chunks: [
      { phrase: "I see", meaning: "알겠다", example: "I see what you mean.", ko: "무슨 말씀인지 알겠어요." },
      { phrase: "see you", meaning: "다시 만나다", example: "I'll see you tomorrow.", ko: "내일 봐요." },
      { phrase: "let's see", meaning: "어디 보자", example: "Let's see how it goes.", ko: "어떻게 되는지 보죠." },
      { phrase: "see to it", meaning: "반드시 처리하다", example: "I'll see to it right away.", ko: "제가 바로 처리하겠습니다." },
    ],
    prompts: [
      { ko: "무슨 말씀인지 알겠어요.", answer: "I see what you mean.", hint: "see what + clause", context: "회의" },
      { ko: "내일 봐요.", answer: "I'll see you tomorrow.", hint: "see + person", context: "약속" },
      { ko: "제가 바로 처리하겠습니다.", answer: "I'll see to it right away.", hint: "see to it", context: "업무" },
    ],
  },
  {
    id: "look",
    word: "LOOK",
    korean: "보다 · 찾아보다 · ~해 보이다",
    image: "의도적으로 시선과 관심을 한 방향에 둠",
    summary: "at, for, into, over 같은 작은 단어와 결합해 보기·찾기·조사·검토로 확장됩니다.",
    forms: "look / looks · looked · looked",
    accent: "#79d9ca",
    tint: "#e7faf6",
    patterns: [
      { frame: "look at + object", meaning: "일부러 보다", example: "Look at this chart.", ko: "이 차트를 보세요." },
      { frame: "look + adjective", meaning: "~해 보이다", example: "You look tired.", ko: "피곤해 보여요." },
      { frame: "look for + object", meaning: "찾다", example: "I'm looking for the latest file.", ko: "최신 파일을 찾고 있어요." },
    ],
    chunks: [
      { phrase: "look into", meaning: "조사하다", example: "I'll look into the issue.", ko: "그 문제를 알아볼게요." },
      { phrase: "look over", meaning: "검토하다", example: "Could you look over this draft?", ko: "이 초안을 검토해 주시겠어요?" },
      { phrase: "look forward to", meaning: "기대하다", example: "I look forward to working with you.", ko: "함께 일하게 되어 기대됩니다." },
      { phrase: "look out", meaning: "조심하다", example: "Look out for hidden costs.", ko: "숨은 비용을 조심하세요." },
    ],
    prompts: [
      { ko: "그 문제를 알아볼게요.", answer: "I'll look into the issue.", hint: "look into", context: "문제 해결" },
      { ko: "이 초안을 검토해 주시겠어요?", answer: "Could you look over this draft?", hint: "look over", context: "업무" },
      { ko: "함께 일하게 되어 기대됩니다.", answer: "I look forward to working with you.", hint: "look forward to + -ing", context: "업무" },
    ],
  },
  {
    id: "watch",
    word: "WATCH",
    korean: "지켜보다 · 관찰하다 · 조심하다",
    image: "움직이거나 변하는 대상을 일정 시간 계속 봄",
    summary: "영상이나 움직임을 보는 것부터 진행 상황을 관찰하고 위험을 주의하는 표현까지 연결됩니다.",
    forms: "watch / watches · watched · watched",
    accent: "#f1a0c1",
    tint: "#fff0f6",
    patterns: [
      { frame: "watch + object", meaning: "지켜보다", example: "Let's watch the demo.", ko: "데모를 지켜보죠." },
      { frame: "watch how + clause", meaning: "어떻게 하는지 지켜보다", example: "Watch how she handles it.", ko: "그녀가 어떻게 처리하는지 보세요." },
      { frame: "watch for + noun", meaning: "~을 주의 깊게 찾다", example: "Watch for any changes.", ko: "변화가 있는지 잘 보세요." },
    ],
    chunks: [
      { phrase: "watch out", meaning: "위험을 조심하다", example: "Watch out for scams.", ko: "사기 조심하세요." },
      { phrase: "watch closely", meaning: "면밀히 지켜보다", example: "We'll watch the numbers closely.", ko: "수치를 면밀히 지켜보겠습니다." },
      { phrase: "watch your step", meaning: "발밑·행동을 조심하다", example: "Watch your step on the stairs.", ko: "계단에서 발밑 조심하세요." },
      { phrase: "watch the time", meaning: "시간을 살피다", example: "We need to watch the time.", ko: "시간을 잘 봐야 해요." },
    ],
    prompts: [
      { ko: "수치를 면밀히 지켜보겠습니다.", answer: "We'll watch the numbers closely.", hint: "watch + object + closely", context: "업무" },
      { ko: "변화가 있는지 잘 보세요.", answer: "Watch for any changes.", hint: "watch for", context: "업무" },
      { ko: "시간을 잘 봐야 해요.", answer: "We need to watch the time.", hint: "watch the time", context: "회의" },
    ],
  },
  {
    id: "mean",
    word: "MEAN",
    korean: "뜻하다 · 의도하다 · 진심이다",
    image: "말이나 행동이 가리키는 실제 뜻과 의도를 밝힘",
    summary: "오해를 풀고 뜻을 확인하며, 의도하지 않았던 행동을 설명할 때 꼭 필요한 동사입니다.",
    forms: "mean / means · meant · meant",
    accent: "#c9adff",
    tint: "#f3edff",
    patterns: [
      { frame: "mean + clause", meaning: "~라는 뜻이다", example: "This means we need more time.", ko: "이건 시간이 더 필요하다는 뜻이에요." },
      { frame: "mean to + verb", meaning: "~할 의도이다", example: "I meant to call you.", ko: "전화하려고 했어요." },
      { frame: "be meant to + verb / be", meaning: "~하도록 의도되다", example: "This is meant to be temporary.", ko: "이건 임시용입니다." },
    ],
    chunks: [
      { phrase: "what do you mean", meaning: "무슨 뜻인지 묻다", example: "What do you mean by that?", ko: "그게 무슨 뜻인가요?" },
      { phrase: "I mean it", meaning: "진심이다", example: "I mean it. You did great.", ko: "진심이에요. 정말 잘했어요." },
      { phrase: "didn't mean to", meaning: "일부러 한 것이 아니다", example: "I didn't mean to interrupt.", ko: "일부러 끼어든 건 아니에요." },
      { phrase: "by that I mean", meaning: "뜻을 구체화하다", example: "By that, I mean the final deadline.", ko: "그 말은 최종 마감일을 뜻합니다." },
    ],
    prompts: [
      { ko: "그게 무슨 뜻인가요?", answer: "What do you mean by that?", hint: "mean by", context: "회의" },
      { ko: "일부러 끼어든 건 아니에요.", answer: "I didn't mean to interrupt.", hint: "didn't mean to", context: "회의" },
      { ko: "이건 임시용입니다.", answer: "This is meant to be temporary.", hint: "be meant to", context: "업무" },
    ],
  },
  {
    id: "say",
    word: "SAY",
    korean: "말하다 · 의견을 밝히다",
    image: "누구보다 말의 내용 자체를 밖으로 꺼냄",
    summary: "say 뒤에는 말의 내용이 오고, 사람을 붙일 때는 say to를 쓰는 어순이 핵심입니다.",
    forms: "say / says · said · said",
    accent: "#ff9e87",
    tint: "#fff0eb",
    patterns: [
      { frame: "say + content", meaning: "무엇을 말하다", example: "What did she say?", ko: "그분이 뭐라고 했어요?" },
      { frame: "say to + person", meaning: "누구에게 말하다", example: "I said hello to the team.", ko: "팀에 인사했어요." },
      { frame: "I'd say + clause", meaning: "의견을 부드럽게 말하다", example: "I'd say we're ready.", ko: "제 생각엔 준비된 것 같아요." },
    ],
    chunks: [
      { phrase: "say that again", meaning: "다시 말하다", example: "Could you say that again?", ko: "다시 말씀해 주시겠어요?" },
      { phrase: "say no", meaning: "거절하다", example: "It's okay to say no.", ko: "거절해도 괜찮아요." },
      { phrase: "let's say", meaning: "가정하다", example: "Let's say we launch in May.", ko: "5월에 출시한다고 가정해 보죠." },
      { phrase: "needless to say", meaning: "말할 필요도 없이", example: "Needless to say, quality comes first.", ko: "말할 것도 없이 품질이 우선입니다." },
    ],
    prompts: [
      { ko: "다시 말씀해 주시겠어요?", answer: "Could you say that again?", hint: "say + content", context: "회의" },
      { ko: "제 생각엔 준비된 것 같아요.", answer: "I'd say we're ready.", hint: "I'd say + clause", context: "회의" },
      { ko: "5월에 출시한다고 가정해 보죠.", answer: "Let's say we launch in May.", hint: "let's say", context: "회의" },
    ],
  },
  {
    id: "tell",
    word: "TELL",
    korean: "알려주다 · 말해주다",
    image: "정보를 특정 사람에게 직접 전달함",
    summary: "tell 바로 뒤에는 사람이 옵니다. tell me, tell the team처럼 수신자를 먼저 세우세요.",
    forms: "tell / tells · told · told",
    accent: "#7ecde8",
    tint: "#eaf8fc",
    patterns: [
      { frame: "tell + person + content", meaning: "누구에게 알려주다", example: "Tell me what happened.", ko: "무슨 일이 있었는지 말해 주세요." },
      { frame: "tell + person + to", meaning: "~에게 하라고 말하다", example: "I told him to wait.", ko: "그에게 기다리라고 했어요." },
      { frame: "tell from", meaning: "구별하다·알아보다", example: "It's hard to tell from this chart.", ko: "이 차트만으로는 판단하기 어려워요." },
    ],
    chunks: [
      { phrase: "tell me about it", meaning: "상대의 말에 강하게 공감하다", example: "Tell me about it. This week has been exhausting.", ko: "그러게 말이에요. 이번 주는 정말 힘들었어요." },
      { phrase: "tell the truth", meaning: "사실대로 말하다", example: "To tell the truth, I'm concerned.", ko: "솔직히 말씀드리면 걱정됩니다." },
      { phrase: "tell apart", meaning: "구별하다", example: "I can't tell these versions apart.", ko: "이 버전들을 구별하기 어렵네요." },
      { phrase: "I'll tell you what", meaning: "제안·생각을 꺼내다", example: "I'll tell you what: let's test both.", ko: "이렇게 하죠. 둘 다 테스트해 봅시다." },
    ],
    prompts: [
      { ko: "무슨 일이 있었는지 말해 주세요.", answer: "Tell me what happened.", hint: "tell + person + content", context: "업무" },
      { ko: "솔직히 말씀드리면 걱정됩니다.", answer: "To tell the truth, I'm concerned.", hint: "to tell the truth", context: "회의" },
      { ko: "이 버전들을 구별하기 어렵네요.", answer: "I can't tell these versions apart.", hint: "tell apart", context: "업무" },
    ],
  },
  {
    id: "ask",
    word: "ASK",
    korean: "묻다 · 요청하다 · 부탁하다",
    image: "답이나 행동을 얻기 위해 상대에게 공을 건넴",
    summary: "질문은 ask a question, 요청은 ask for, 사람에게 행동을 부탁할 때는 ask someone to를 씁니다.",
    forms: "ask / asks · asked · asked",
    accent: "#ffd06f",
    tint: "#fff7df",
    patterns: [
      { frame: "ask + person + question", meaning: "누구에게 묻다", example: "Can I ask you something?", ko: "뭐 하나 여쭤봐도 될까요?" },
      { frame: "ask for + noun", meaning: "~을 요청하다", example: "I'll ask for more time.", ko: "시간을 더 요청할게요." },
      { frame: "ask + person + to", meaning: "~에게 부탁하다", example: "I asked her to review it.", ko: "그분에게 검토를 부탁했어요." },
    ],
    chunks: [
      { phrase: "ask around", meaning: "여러 사람에게 물어보다", example: "I'll ask around and let you know.", ko: "주변에 물어보고 알려드릴게요." },
      { phrase: "ask about", meaning: "~에 대해 묻다", example: "They asked about the timeline.", ko: "그쪽에서 일정에 대해 물었어요." },
      { phrase: "ask someone a favor", meaning: "누군가에게 부탁하다", example: "Can I ask you a favor?", ko: "부탁 하나 드려도 될까요?" },
      { phrase: "ask yourself", meaning: "스스로 자문하다", example: "Ask yourself what success looks like.", ko: "성공이 어떤 모습인지 스스로 물어보세요." },
    ],
    prompts: [
      { ko: "뭐 하나 여쭤봐도 될까요?", answer: "Can I ask you something?", hint: "ask + person", context: "회의" },
      { ko: "시간을 더 요청할게요.", answer: "I'll ask for more time.", hint: "ask for", context: "업무" },
      { ko: "그분에게 검토를 부탁했어요.", answer: "I asked her to review it.", hint: "ask + person + to", context: "업무" },
    ],
  },
  {
    id: "talk",
    word: "TALK",
    korean: "대화하다 · 논의하다",
    image: "사람 사이에서 말이 오가며 생각을 맞춰 감",
    summary: "사람과는 talk to/with, 주제와는 talk about, 문제는 talk through로 연결합니다.",
    forms: "talk / talks · talked · talked",
    accent: "#b6dd84",
    tint: "#f1f9e8",
    patterns: [
      { frame: "talk to / with + person", meaning: "누구와 대화하다", example: "Can we talk for a minute?", ko: "잠깐 이야기할 수 있을까요?" },
      { frame: "talk about + topic", meaning: "~에 대해 논의하다", example: "Let's talk about the budget.", ko: "예산에 대해 이야기해 보죠." },
      { frame: "talk through + issue", meaning: "차근차근 논의하다", example: "Let's talk through the options.", ko: "선택지를 하나씩 논의해 보죠." },
    ],
    chunks: [
      { phrase: "talk it over", meaning: "충분히 상의하다", example: "We need to talk it over.", ko: "그건 충분히 상의해야 해요." },
      { phrase: "talk through", meaning: "단계별로 설명·논의하다", example: "Can you talk me through the process?", ko: "과정을 차근차근 설명해 주시겠어요?" },
      { phrase: "talk someone into", meaning: "설득하다", example: "She talked us into trying it.", ko: "그녀가 우리를 설득해 시도하게 했어요." },
      { phrase: "talk to you later", meaning: "나중에 이야기하다", example: "I'll talk to you later.", ko: "나중에 다시 이야기할게요." },
    ],
    prompts: [
      { ko: "예산에 대해 이야기해 보죠.", answer: "Let's talk about the budget.", hint: "talk about", context: "회의" },
      { ko: "선택지를 하나씩 논의해 보죠.", answer: "Let's talk through the options.", hint: "talk through", context: "회의" },
      { ko: "과정을 차근차근 설명해 주시겠어요?", answer: "Can you talk me through the process?", hint: "talk someone through", context: "업무" },
    ],
  },
  {
    id: "turn",
    word: "TURN",
    korean: "돌리다 · 바뀌다 · 켜고 끄다",
    image: "방향이나 상태를 다른 쪽으로 전환함",
    summary: "방향 전환, 상태 변화, 기기 조작, 결과를 말할 때 작은 단어와 함께 자주 사용합니다.",
    forms: "turn / turns · turned · turned",
    accent: "#ffb06e",
    tint: "#fff2e5",
    patterns: [
      { frame: "turn + direction", meaning: "방향을 바꾸다", example: "Turn left at the corner.", ko: "모퉁이에서 좌회전하세요." },
      { frame: "turn + adjective", meaning: "~한 상태가 되다", example: "The screen turned black.", ko: "화면이 검게 변했어요." },
      { frame: "turn + object + on/off", meaning: "켜다·끄다", example: "Please turn your camera on.", ko: "카메라를 켜 주세요." },
    ],
    chunks: [
      { phrase: "turn out", meaning: "~로 판명되다", example: "It turned out better than expected.", ko: "예상보다 결과가 좋았어요." },
      { phrase: "turn down", meaning: "줄이다·거절하다", example: "They turned down the proposal.", ko: "그들이 제안을 거절했어요." },
      { phrase: "turn around", meaning: "상황을 반전시키다", example: "We can turn this around.", ko: "이 상황을 반전시킬 수 있어요." },
      { phrase: "your turn", meaning: "당신 차례", example: "It's your turn to present.", ko: "이제 발표하실 차례예요." },
    ],
    prompts: [
      { ko: "카메라를 켜 주세요.", answer: "Please turn your camera on.", hint: "turn + object + on", context: "온라인 회의" },
      { ko: "예상보다 결과가 좋았어요.", answer: "It turned out better than expected.", hint: "turn out", context: "업무" },
      { ko: "이 상황을 반전시킬 수 있어요.", answer: "We can turn this around.", hint: "turn around", context: "문제 해결" },
    ],
  },
  {
    id: "run",
    word: "RUN",
    korean: "달리다 · 운영하다 · 돌아가다",
    image: "사람·시간·시스템이 계속 앞으로 움직임",
    summary: "사업을 운영하고, 시스템이 작동하며, 시간이나 자원이 소진되는 흐름까지 표현합니다.",
    forms: "run / runs · ran · run",
    accent: "#85b8ff",
    tint: "#ebf3ff",
    patterns: [
      { frame: "run + business / project", meaning: "운영하다", example: "She runs the project.", ko: "그분이 프로젝트를 운영해요." },
      { frame: "be running + adjective", meaning: "진행 상태이다", example: "We're running late.", ko: "일정이 늦어지고 있어요." },
      { frame: "run + system / test", meaning: "작동·실행하다", example: "Let's run one more test.", ko: "테스트를 한 번 더 돌려보죠." },
    ],
    chunks: [
      { phrase: "run out of", meaning: "~이 다 떨어지다", example: "We're running out of time.", ko: "시간이 부족해지고 있어요." },
      { phrase: "run through", meaning: "빠르게 검토·설명하다", example: "Let me run through the key points.", ko: "핵심을 빠르게 짚어볼게요." },
      { phrase: "run into", meaning: "문제에 부딪히다", example: "We ran into a technical issue.", ko: "기술적인 문제에 부딪혔어요." },
      { phrase: "run by", meaning: "의견을 구하다", example: "Can I run an idea by you?", ko: "아이디어 하나 여쭤봐도 될까요?" },
    ],
    prompts: [
      { ko: "시간이 부족해지고 있어요.", answer: "We're running out of time.", hint: "run out of", context: "회의" },
      { ko: "핵심을 빠르게 짚어볼게요.", answer: "Let me run through the key points.", hint: "run through", context: "회의" },
      { ko: "기술적인 문제에 부딪혔어요.", answer: "We ran into a technical issue.", hint: "run into", context: "업무" },
    ],
  },
  {
    id: "work",
    word: "WORK",
    korean: "일하다 · 작동하다 · 효과가 있다",
    image: "사람이나 방법, 기계가 목적대로 기능함",
    summary: "직업과 업무뿐 아니라 일정이 맞는지, 아이디어가 통하는지, 기기가 작동하는지도 표현합니다.",
    forms: "work / works · worked · worked",
    accent: "#a7cf75",
    tint: "#f0f8e7",
    patterns: [
      { frame: "work + place / for", meaning: "일하다", example: "I work from home on Fridays.", ko: "금요일에는 재택근무해요." },
      { frame: "work on + object", meaning: "~을 작업하다", example: "We're working on the proposal.", ko: "제안서를 작업 중입니다." },
      { frame: "time / plan + work for + person", meaning: "일정·방법이 맞다", example: "Does Tuesday work for you?", ko: "화요일 괜찮으세요?" },
    ],
    chunks: [
      { phrase: "work out", meaning: "잘 해결되다·계산하다", example: "I'm sure it'll work out.", ko: "분명 잘 해결될 거예요." },
      { phrase: "work around", meaning: "우회 해결하다", example: "We found a way to work around it.", ko: "우회해서 해결할 방법을 찾았어요." },
      { phrase: "make it work", meaning: "되게 만들다", example: "Let's find a way to make it work.", ko: "되게 만들 방법을 찾아보죠." },
      { phrase: "whatever works", meaning: "되는 방법이면 무엇이든", example: "Whatever works for the team.", ko: "팀에 맞는 방법이면 뭐든 좋아요." },
    ],
    prompts: [
      { ko: "화요일 괜찮으세요?", answer: "Does Tuesday work for you?", hint: "work for + person", context: "일정" },
      { ko: "제안서를 작업 중입니다.", answer: "We're working on the proposal.", hint: "work on", context: "업무" },
      { ko: "분명 잘 해결될 거예요.", answer: "I'm sure it'll work out.", hint: "work out", context: "격려" },
    ],
  },
  {
    id: "call",
    word: "CALL",
    korean: "부르다 · 전화하다 · ~라고 이름 붙이다",
    image: "이름을 붙이거나 멀리 있는 사람을 불러 연결함",
    summary: "전화뿐 아니라 이름 붙이기, 회의를 끝내기, 결정을 취소하기 같은 업무 표현에도 자주 씁니다.",
    forms: "call / calls · called · called",
    accent: "#d4a5ff",
    tint: "#f7edff",
    patterns: [
      { frame: "call + person", meaning: "전화하다·부르다", example: "I'll call you after lunch.", ko: "점심 후에 전화드릴게요." },
      { frame: "call + object + noun", meaning: "~라고 부르다", example: "We call this the pilot phase.", ko: "이걸 파일럿 단계라고 부릅니다." },
      { frame: "call for + noun", meaning: "~을 요구하다", example: "This calls for a different approach.", ko: "이건 다른 접근이 필요합니다." },
    ],
    chunks: [
      { phrase: "call back", meaning: "다시 전화하다", example: "I'll call you back in ten minutes.", ko: "10분 뒤에 다시 전화드릴게요." },
      { phrase: "call it a day", meaning: "오늘 일을 마치다", example: "Let's call it a day.", ko: "오늘은 여기까지 하죠." },
      { phrase: "call off", meaning: "취소하다", example: "They called off the meeting.", ko: "그들이 회의를 취소했어요." },
      { phrase: "give me a call", meaning: "전화하다", example: "Give me a call when you're free.", ko: "시간 될 때 전화 주세요." },
    ],
    prompts: [
      { ko: "10분 뒤에 다시 전화드릴게요.", answer: "I'll call you back in ten minutes.", hint: "call back", context: "업무" },
      { ko: "오늘은 여기까지 하죠.", answer: "Let's call it a day.", hint: "call it a day", context: "업무" },
      { ko: "그들이 회의를 취소했어요.", answer: "They called off the meeting.", hint: "call off", context: "회의" },
    ],
  },
  {
    id: "break",
    word: "BREAK",
    korean: "깨다 · 고장 나다 · 나누다",
    image: "하나로 이어진 상태를 끊거나 작은 부분으로 분리함",
    summary: "물건과 규칙을 깨는 뜻부터 휴식, 분석, 관계 형성, 소식 전달까지 다양한 덩어리 표현을 만듭니다.",
    forms: "break / breaks · broke · broken",
    accent: "#ff9f9b",
    tint: "#fff0ef",
    patterns: [
      { frame: "break + object", meaning: "깨다·어기다", example: "We can't break the agreement.", ko: "합의를 어길 수는 없어요." },
      { frame: "thing + break", meaning: "고장 나다", example: "The printer broke again.", ko: "프린터가 또 고장 났어요." },
      { frame: "break into + parts", meaning: "나누다", example: "Let's break this into three steps.", ko: "이걸 세 단계로 나누죠." },
    ],
    chunks: [
      { phrase: "take a break", meaning: "쉬다", example: "Let's take a short break.", ko: "잠깐 쉬었다 하죠." },
      { phrase: "break it down", meaning: "나눠 설명하다", example: "Let me break it down.", ko: "하나씩 나눠 설명드릴게요." },
      { phrase: "break the ice", meaning: "어색함을 풀다", example: "A quick introduction will break the ice.", ko: "짧은 소개가 어색함을 풀어줄 거예요." },
      { phrase: "break the news", meaning: "소식을 전하다", example: "We need to break the news carefully.", ko: "그 소식을 신중하게 전해야 해요." },
    ],
    prompts: [
      { ko: "이걸 세 단계로 나누죠.", answer: "Let's break this into three steps.", hint: "break into", context: "회의" },
      { ko: "하나씩 나눠 설명드릴게요.", answer: "Let me break it down.", hint: "break down", context: "설명" },
      { ko: "잠깐 쉬었다 하죠.", answer: "Let's take a short break.", hint: "take a break", context: "회의" },
    ],
  },
];
