export const meetingCategories = [
  { id: "opening", ko: "회의 시작", en: "Opening the meeting" },
  { id: "agenda", ko: "안건 · 순서", en: "Agenda & sequencing" },
  { id: "opinions", ko: "의견 제시", en: "Giving opinions" },
  { id: "agreeing", ko: "동의 · 지지", en: "Agreeing & supporting" },
  { id: "disagreeing", ko: "부분 동의 · 반대", en: "Disagreeing politely" },
  { id: "clarifying", ko: "질문 · 명확화", en: "Asking & clarifying" },
  { id: "confirming", ko: "확인 · 재확인", en: "Confirming & checking" },
  { id: "suggestions", ko: "제안", en: "Making suggestions" },
  { id: "delegating", ko: "요청 · 위임", en: "Requesting & delegating" },
  { id: "updates", ko: "진행 상황 · 업데이트", en: "Status & updates" },
  { id: "scheduling", ko: "시간 · 일정", en: "Time & scheduling" },
  { id: "turn-taking", ko: "끼어들기 · 발언권", en: "Interrupting & turn-taking" },
  { id: "wrapping-up", ko: "요약 · 마무리", en: "Summarizing & wrapping up" },
  { id: "follow-up", ko: "후속 조치", en: "Follow-up & action items" },
  { id: "small-talk", ko: "스몰토크 · 인사", en: "Small talk & greetings" },
  { id: "virtual", ko: "온라인 · 화상 미팅", en: "Virtual meetings" },
];

const sentenceRows = [
  {
    no: 1,
    categoryId: "opening",
    en: "Let's get started, everyone.",
    ko: "자, 다들 시작합시다.",
    verbId: "get",
    pattern: "Let's get + past participle",
    variants: [
      { en: "Let's get started with the budget review.", ko: "예산 검토부터 시작하죠." },
      { en: "Let's get started before the client joins.", ko: "고객이 들어오기 전에 시작하죠." },
    ],
  },
  {
    no: 2,
    categoryId: "opening",
    en: "Shall we begin now that everyone's here?",
    ko: "다 모였으니 시작할까요?",
    verbId: null,
    focus: "BEGIN",
    pattern: "Shall we + verb now that + clause?",
    variants: [
      { en: "Shall we begin now that the finance team is here?", ko: "재무팀이 다 왔으니 시작할까요?" },
      { en: "Shall we begin since everyone has the materials?", ko: "모두 자료를 받았으니 시작할까요?" },
    ],
  },
  {
    no: 3,
    categoryId: "opening",
    en: "Thanks for joining today's meeting.",
    ko: "오늘 회의에 참석해 주셔서 감사합니다.",
    verbId: null,
    focus: "THANKS FOR",
    pattern: "Thanks for + noun / -ing",
    variants: [
      { en: "Thanks for joining this morning's planning session.", ko: "오늘 아침 기획 회의에 참석해 주셔서 감사합니다." },
      { en: "Thanks for making time for this review meeting.", ko: "이번 검토 회의에 시간 내주셔서 감사합니다." },
    ],
  },
  {
    no: 4,
    categoryId: "opening",
    en: "Let's wait a couple of minutes for the others.",
    ko: "다른 분들을 위해 몇 분 기다리죠.",
    verbId: "let",
    pattern: "Let's wait + time + for + person",
    variants: [
      { en: "Let's wait another minute for the regional team.", ko: "지역 팀을 위해 1분만 더 기다리죠." },
      { en: "Let's wait a few minutes for the client to join.", ko: "고객이 들어올 수 있게 몇 분 기다리죠." },
    ],
  },
  {
    no: 5,
    categoryId: "opening",
    en: "Can everyone hear me okay?",
    ko: "다들 잘 들리세요?",
    verbId: null,
    focus: "HEAR",
    pattern: "Can everyone hear + object + adverb?",
    variants: [
      { en: "Can everyone hear me without any echo?", ko: "다들 제 목소리 울림 없이 잘 들리세요?" },
      { en: "Can everyone hear the presentation audio clearly?", ko: "다들 발표 음성 잘 들리세요?" },
    ],
  },
  {
    no: 6,
    categoryId: "opening",
    en: "Let's dive right into the agenda.",
    ko: "바로 안건으로 들어가죠.",
    verbId: null,
    focus: "DIVE INTO",
    pattern: "Let's dive + adverb + into + noun",
    variants: [
      { en: "Let's dive right into the quarterly results.", ko: "바로 분기 실적으로 들어가죠." },
      { en: "Let's dive straight into the main decision.", ko: "바로 핵심 결정 사항으로 들어가죠." },
    ],
  },
  {
    no: 7,
    categoryId: "agenda",
    en: "Let's go over the agenda first.",
    ko: "먼저 안건을 살펴보죠.",
    verbId: "go",
    pattern: "Let's go over + noun + first",
    variants: [
      { en: "Let's go over today's priorities first.", ko: "먼저 오늘의 우선순위를 살펴보죠." },
      { en: "Let's go over the revised agenda before we begin.", ko: "시작하기 전에 수정된 안건을 살펴보죠." },
    ],
  },
  {
    no: 8,
    categoryId: "agenda",
    en: "First, let's talk about the project timeline.",
    ko: "먼저 프로젝트 일정부터 이야기하죠.",
    verbId: "talk",
    pattern: "First, let's talk about + noun",
    variants: [
      { en: "First, let's talk about the hiring plan.", ko: "먼저 채용 계획부터 이야기하죠." },
      { en: "First, let's talk about the customer feedback.", ko: "먼저 고객 피드백부터 이야기하죠." },
    ],
  },
  {
    no: 9,
    categoryId: "agenda",
    en: "There are three things we need to cover today.",
    ko: "오늘 다룰 게 세 가지 있습니다.",
    verbId: "need",
    pattern: "There are + number + things we need to + verb",
    variants: [
      { en: "There are two decisions we need to make today.", ko: "오늘 내려야 할 결정이 두 가지 있습니다." },
      { en: "There are four updates we need to cover this morning.", ko: "오늘 아침 다뤄야 할 업데이트가 네 가지 있습니다." },
    ],
  },
  {
    no: 10,
    categoryId: "agenda",
    en: "Let's move on to the next point.",
    ko: "다음 안건으로 넘어가죠.",
    verbId: null,
    focus: "MOVE ON",
    pattern: "Let's move on to + noun",
    variants: [
      { en: "Let's move on to the budget discussion.", ko: "예산 논의로 넘어가죠." },
      { en: "Let's move on to the final item on the agenda.", ko: "마지막 안건으로 넘어가죠." },
    ],
  },
  {
    no: 11,
    categoryId: "agenda",
    en: "Let's come back to that issue later.",
    ko: "그 문제는 나중에 다시 다루죠.",
    verbId: "come",
    pattern: "Let's come back to + noun + time",
    variants: [
      { en: "Let's come back to the pricing question after lunch.", ko: "가격 문제는 점심 후에 다시 다루죠." },
      { en: "Let's come back to the staffing issue once we have the data.", ko: "데이터가 준비되면 인력 문제를 다시 다루죠." },
    ],
  },
  {
    no: 12,
    categoryId: "agenda",
    en: "Let's put that aside for now and continue.",
    ko: "그건 일단 미뤄두고 계속하죠.",
    verbId: "put",
    pattern: "Let's put + noun + aside and + verb",
    variants: [
      { en: "Let's put the contract question aside for now and continue.", ko: "계약 관련 질문은 일단 미뤄두고 계속하죠." },
      { en: "Let's put the technical details aside and stay on schedule.", ko: "기술적인 세부 사항은 잠시 미뤄두고 일정대로 진행하죠." },
    ],
  },
  {
    no: 13,
    categoryId: "opinions",
    en: "I think we should focus on the deadline first.",
    ko: "제 생각엔 마감부터 집중해야 할 것 같아요.",
    verbId: "think",
    pattern: "I think we should focus on + noun + first",
    variants: [
      { en: "I think we should focus on customer retention first.", ko: "제 생각엔 고객 유지에 먼저 집중해야 할 것 같아요." },
      { en: "I think we should focus on the highest-risk item first.", ko: "제 생각엔 위험이 가장 큰 항목에 먼저 집중해야 할 것 같아요." },
    ],
  },
  {
    no: 14,
    categoryId: "opinions",
    en: "In my opinion, this plan needs more testing.",
    ko: "제 의견으론 이 계획은 테스트가 더 필요해요.",
    verbId: "need",
    pattern: "In my opinion, + noun + needs + noun",
    variants: [
      { en: "In my opinion, this proposal needs clearer metrics.", ko: "제 의견으론 이 제안에는 더 명확한 지표가 필요해요." },
      { en: "In my opinion, the new workflow needs more testing.", ko: "제 의견으론 새 업무 절차는 테스트가 더 필요해요." },
    ],
  },
  {
    no: 15,
    categoryId: "opinions",
    en: "I'd say we're ready to move forward.",
    ko: "저는 진행할 준비가 됐다고 봅니다.",
    verbId: "be",
    pattern: "I'd say we're ready to + verb",
    variants: [
      { en: "I'd say we're ready to present this to the client.", ko: "저는 이걸 고객에게 제시할 준비가 됐다고 봅니다." },
      { en: "I'd say we're ready to approve the final version.", ko: "저는 최종안을 승인할 준비가 됐다고 봅니다." },
    ],
  },
  {
    no: 16,
    categoryId: "opinions",
    en: "From my point of view, the budget is too tight.",
    ko: "제 관점에선 예산이 너무 빠듯해요.",
    verbId: "be",
    pattern: "From my point of view, + noun + is too + adjective",
    variants: [
      { en: "From my point of view, the timeline is too aggressive.", ko: "제 관점에선 일정이 너무 빠듯해요." },
      { en: "From my point of view, the current scope is too broad.", ko: "제 관점에선 현재 범위가 너무 넓어요." },
    ],
  },
  {
    no: 17,
    categoryId: "opinions",
    en: "The way I see it, we have two options.",
    ko: "제가 보기엔 두 가지 선택지가 있어요.",
    verbId: "see",
    pattern: "The way I see it, we have + noun",
    variants: [
      { en: "The way I see it, we have three realistic options.", ko: "제가 보기엔 현실적인 선택지가 세 가지 있어요." },
      { en: "The way I see it, we have one major obstacle.", ko: "제가 보기엔 큰 장애물이 하나 있어요." },
    ],
  },
  {
    no: 18,
    categoryId: "opinions",
    en: "If you ask me, we should delay the launch.",
    ko: "제 생각을 말하자면 출시를 미뤄야 해요.",
    verbId: "ask",
    pattern: "If you ask me, we should + verb",
    variants: [
      { en: "If you ask me, we should postpone the rollout.", ko: "제 생각을 말하자면 배포를 미뤄야 해요." },
      { en: "If you ask me, we should reduce the initial scope.", ko: "제 생각을 말하자면 초기 범위를 줄여야 해요." },
    ],
  },
  {
    no: 19,
    categoryId: "opinions",
    en: "I feel like we're missing something here.",
    ko: "여기서 뭔가 놓치고 있는 것 같아요.",
    verbId: null,
    focus: "FEEL LIKE",
    pattern: "I feel like we're missing + noun",
    variants: [
      { en: "I feel like we're missing a key requirement here.", ko: "여기서 핵심 요구 사항 하나를 놓치고 있는 것 같아요." },
      { en: "I feel like we're missing the customer's perspective.", ko: "고객의 관점을 놓치고 있는 것 같아요." },
    ],
  },
  {
    no: 20,
    categoryId: "opinions",
    en: "My take is that the risk is worth it.",
    ko: "제 생각은 그 위험은 감수할 만하다는 거예요.",
    verbId: "be",
    pattern: "My take is that + noun + is worth + noun",
    variants: [
      { en: "My take is that the opportunity is worth the risk.", ko: "제 생각은 그 기회가 위험을 감수할 만하다는 거예요." },
      { en: "My take is that the extra effort is worth it.", ko: "제 생각은 추가 노력을 들일 가치가 있다는 거예요." },
    ],
  },
  {
    no: 21,
    categoryId: "agreeing",
    en: "I agree with your point completely.",
    ko: "말씀에 전적으로 동의합니다.",
    verbId: null,
    focus: "AGREE",
    pattern: "I agree with + noun + completely",
    variants: [
      { en: "I agree with your recommendation completely.", ko: "제안하신 내용에 전적으로 동의합니다." },
      { en: "I agree with the revised timeline completely.", ko: "수정된 일정에 전적으로 동의합니다." },
    ],
  },
  {
    no: 22,
    categoryId: "agreeing",
    en: "That's a really good point.",
    ko: "정말 좋은 지적이에요.",
    verbId: "be",
    pattern: "That's a really + adjective + noun",
    variants: [
      { en: "That's a really useful suggestion.", ko: "정말 유용한 제안이에요." },
      { en: "That's a really important observation.", ko: "정말 중요한 지적이에요." },
    ],
  },
  {
    no: 23,
    categoryId: "agreeing",
    en: "That makes a lot of sense to me.",
    ko: "저한텐 아주 말이 되네요.",
    verbId: "make",
    pattern: "That makes a lot of sense + context",
    variants: [
      { en: "That makes a lot of sense from a cost perspective.", ko: "비용 관점에서 아주 말이 되네요." },
      { en: "That makes a lot of sense for the pilot phase.", ko: "시범 단계에는 아주 합리적이네요." },
    ],
  },
  {
    no: 24,
    categoryId: "agreeing",
    en: "Exactly, that's what I was thinking.",
    ko: "정확해요, 저도 그 생각이었어요.",
    verbId: null,
    focus: "AGREEING",
    pattern: "Exactly, that's what I was + thinking/suggesting",
    variants: [
      { en: "Exactly, that's what I was about to suggest.", ko: "맞아요, 저도 바로 그걸 제안하려고 했어요." },
      { en: "Exactly, that's what I was thinking about the launch.", ko: "맞아요, 저도 출시에 대해 그렇게 생각하고 있었어요." },
    ],
  },
  {
    no: 25,
    categoryId: "agreeing",
    en: "I'm with you on that one.",
    ko: "그 점은 저도 같은 생각이에요.",
    verbId: "be",
    pattern: "I'm with you on + noun",
    variants: [
      { en: "I'm with you on keeping the scope small.", ko: "범위를 작게 유지하자는 점은 저도 같은 생각이에요." },
      { en: "I'm with you on delaying the announcement.", ko: "발표를 미루자는 점은 저도 같은 생각이에요." },
    ],
  },
  {
    no: 26,
    categoryId: "agreeing",
    en: "That's a fair point, I'll admit.",
    ko: "인정할게요, 일리 있는 말이에요.",
    verbId: "be",
    pattern: "That's a fair point + context",
    variants: [
      { en: "That's a fair point about the added cost, I have to admit.", ko: "추가 비용에 관한 말씀은 일리 있다고 인정할게요." },
      { en: "That's a fair point, especially given the deadline.", ko: "특히 마감을 고려하면 일리 있는 말이에요." },
    ],
  },
  {
    no: 27,
    categoryId: "agreeing",
    en: "Sounds good to me, let's do it.",
    ko: "좋은 것 같아요, 그렇게 하죠.",
    verbId: "do",
    pattern: "Sounds good to me, let's do + object",
    variants: [
      { en: "Sounds good to me, let's do that next week.", ko: "좋은 것 같아요, 다음 주에 그렇게 하죠." },
      { en: "Sounds good to me, let's do it in two phases.", ko: "좋은 것 같아요, 두 단계로 진행하죠." },
    ],
  },
  {
    no: 28,
    categoryId: "disagreeing",
    en: "I see your point, but the cost is a concern.",
    ko: "무슨 말인지 알겠지만 비용이 걱정이에요.",
    verbId: "see",
    pattern: "I see your point, but + noun + is a concern",
    variants: [
      { en: "I see your point, but the timeline is a concern.", ko: "무슨 말인지 알겠지만 일정이 걱정이에요." },
      { en: "I see your point, but the resource gap is a concern.", ko: "무슨 말인지 알겠지만 인력 부족이 걱정이에요." },
    ],
  },
  {
    no: 29,
    categoryId: "disagreeing",
    en: "That's true, but we don't have enough time.",
    ko: "맞아요, 하지만 시간이 충분치 않아요.",
    verbId: "have",
    pattern: "That's true, but we don't have enough + noun",
    variants: [
      { en: "That's true, but we don't have enough data yet.", ko: "맞아요, 하지만 아직 데이터가 충분하지 않아요." },
      { en: "That's true, but we don't have enough people to support it.", ko: "맞아요, 하지만 이를 지원할 인력이 충분하지 않아요." },
    ],
  },
  {
    no: 30,
    categoryId: "disagreeing",
    en: "I'm not so sure about that approach.",
    ko: "그 방식은 좀 확신이 안 서네요.",
    verbId: "be",
    pattern: "I'm not so sure about + noun",
    variants: [
      { en: "I'm not so sure about changing vendors now.", ko: "지금 업체를 바꾸는 건 좀 확신이 안 서네요." },
      { en: "I'm not so sure about that delivery date.", ko: "그 납기일은 좀 확신이 안 서네요." },
    ],
  },
  {
    no: 31,
    categoryId: "disagreeing",
    en: "I have a slightly different view on this.",
    ko: "이건 제 생각이 조금 달라요.",
    verbId: "have",
    pattern: "I have a slightly different view on + noun",
    variants: [
      { en: "I have a slightly different view on the rollout.", ko: "출시에 대해 제 생각은 조금 달라요." },
      { en: "I have a slightly different view on how we should prioritize this.", ko: "이 일의 우선순위를 정하는 방식에 대해 제 생각은 조금 달라요." },
    ],
  },
  {
    no: 32,
    categoryId: "disagreeing",
    en: "I'm afraid I have to disagree here.",
    ko: "죄송하지만 여기선 동의하기 어렵네요.",
    verbId: "have",
    pattern: "I'm afraid I have to disagree + context",
    variants: [
      { en: "I'm afraid I have to disagree on the timeline.", ko: "죄송하지만 일정에 대해서는 동의하기 어렵네요." },
      { en: "I'm afraid I have to disagree with that conclusion.", ko: "죄송하지만 그 결론에는 동의하기 어렵네요." },
    ],
  },
  {
    no: 33,
    categoryId: "disagreeing",
    en: "I get where you're coming from, but let's be careful.",
    ko: "이해는 되지만 신중하죠.",
    verbId: "get",
    pattern: "I get where you're coming from, but let's + verb",
    variants: [
      { en: "I get where you're coming from, but let's check the assumptions.", ko: "무슨 입장인지 이해는 되지만 가정을 확인해 보죠." },
      { en: "I get where you're coming from, but let's avoid rushing the decision.", ko: "무슨 입장인지 이해는 되지만 성급하게 결정하지는 말죠." },
    ],
  },
  {
    no: 34,
    categoryId: "disagreeing",
    en: "Can we look at this from another angle?",
    ko: "이걸 다른 각도에서 볼 수 있을까요?",
    verbId: "look",
    pattern: "Can we look at + noun + from + angle?",
    variants: [
      { en: "Can we look at the issue from the client's perspective?", ko: "이 문제를 고객의 관점에서 볼 수 있을까요?" },
      { en: "Can we look at the long-term impact instead?", ko: "대신 장기적인 영향을 살펴볼 수 있을까요?" },
    ],
  },
  {
    no: 35,
    categoryId: "clarifying",
    en: "Could you explain that part again?",
    ko: "그 부분 다시 설명해 주시겠어요?",
    verbId: null,
    focus: "EXPLAIN",
    pattern: "Could you explain + noun + again?",
    variants: [
      { en: "Could you explain the pricing model again?", ko: "가격 체계를 다시 설명해 주시겠어요?" },
      { en: "Could you explain how this step works again?", ko: "이 단계가 어떻게 진행되는지 다시 설명해 주시겠어요?" },
    ],
  },
  {
    no: 36,
    categoryId: "clarifying",
    en: "What do you mean by \"phase two\"?",
    ko: "\"2단계\"가 무슨 뜻이죠?",
    verbId: "mean",
    pattern: "What do you mean by + term?",
    variants: [
      { en: "What do you mean by \"limited release\"?", ko: "\"제한 출시\"가 무슨 뜻이죠?" },
      { en: "What do you mean by \"business critical\"?", ko: "\"업무상 필수\"가 무슨 뜻이죠?" },
    ],
  },
  {
    no: 37,
    categoryId: "clarifying",
    en: "Can you go over the numbers again?",
    ko: "수치를 다시 짚어 주시겠어요?",
    verbId: "go",
    pattern: "Can you go over + noun + again?",
    variants: [
      { en: "Can you go over the cost breakdown again?", ko: "비용 내역을 다시 짚어 주시겠어요?" },
      { en: "Can you go over the final milestones again?", ko: "최종 주요 일정을 다시 짚어 주시겠어요?" },
    ],
  },
  {
    no: 38,
    categoryId: "clarifying",
    en: "Could you give us a quick example?",
    ko: "간단한 예를 들어 주시겠어요?",
    verbId: "give",
    pattern: "Could you give us a quick example + context?",
    variants: [
      { en: "Could you give us a quick example from a recent project?", ko: "최근 프로젝트에서 간단한 예를 들어 주시겠어요?" },
      { en: "Could you give us a quick example of the new workflow?", ko: "새 업무 절차의 간단한 예를 들어 주시겠어요?" },
    ],
  },
  {
    no: 39,
    categoryId: "clarifying",
    en: "Just to clarify, is this due on Friday?",
    ko: "명확히 하자면, 이거 금요일까지인가요?",
    verbId: "be",
    pattern: "Just to clarify, is + clause?",
    variants: [
      { en: "Just to clarify, is the draft due this Friday?", ko: "명확히 하자면, 초안은 이번 주 금요일까지인가요?" },
      { en: "Just to clarify, is this approval needed before launch?", ko: "명확히 하자면, 이 승인은 출시 전에 필요한가요?" },
    ],
  },
  {
    no: 40,
    categoryId: "clarifying",
    en: "Can you be more specific about the scope?",
    ko: "범위에 대해 좀 더 구체적으로요?",
    verbId: "be",
    pattern: "Can you be more specific about + noun?",
    variants: [
      { en: "Can you be more specific about the budget limits?", ko: "예산 한도에 대해 좀 더 구체적으로 말씀해 주시겠어요?" },
      { en: "Can you be more specific about what is out of scope?", ko: "범위에 포함되지 않는 항목을 좀 더 구체적으로 말씀해 주시겠어요?" },
    ],
  },
  {
    no: 41,
    categoryId: "clarifying",
    en: "What's the reason for the delay?",
    ko: "지연된 이유가 뭐죠?",
    verbId: "be",
    pattern: "What's the reason for + noun?",
    variants: [
      { en: "What's the reason for the sudden change?", ko: "갑자기 변경된 이유가 뭐죠?" },
      { en: "What's the reason for choosing this vendor?", ko: "이 업체를 선택한 이유가 뭐죠?" },
    ],
  },
  {
    no: 42,
    categoryId: "clarifying",
    en: "How does this process actually work?",
    ko: "이 과정이 실제로 어떻게 되나요?",
    verbId: "work",
    pattern: "How does + noun + actually work?",
    variants: [
      { en: "How does the approval process actually work?", ko: "승인 절차가 실제로 어떻게 되나요?" },
      { en: "How does this feature actually work for end users?", ko: "이 기능은 최종 사용자에게 실제로 어떻게 작동하나요?" },
    ],
  },
  {
    no: 43,
    categoryId: "confirming",
    en: "Let me make sure I understand correctly.",
    ko: "제가 제대로 이해했는지 확인할게요.",
    verbId: "make",
    pattern: "Let me make sure I understand + noun + correctly",
    variants: [
      { en: "Let me make sure I understand the next step correctly.", ko: "제가 다음 단계를 제대로 이해했는지 확인할게요." },
      { en: "Let me make sure I understand your recommendation correctly.", ko: "제가 제안하신 내용을 제대로 이해했는지 확인할게요." },
    ],
  },
  {
    no: 44,
    categoryId: "confirming",
    en: "So you're saying we need more budget?",
    ko: "그러니까 예산이 더 필요하다는 말씀이죠?",
    verbId: "say",
    pattern: "So you're saying we need + noun?",
    variants: [
      { en: "So you're saying we need another designer?", ko: "그러니까 디자이너가 한 명 더 필요하다는 말씀이죠?" },
      { en: "So you're saying we need to revise the launch date?", ko: "그러니까 출시일을 수정해야 한다는 말씀이죠?" },
    ],
  },
  {
    no: 45,
    categoryId: "confirming",
    en: "Just to be clear, who owns this task?",
    ko: "확실히 하자면, 이 일은 누가 맡죠?",
    verbId: "be",
    pattern: "Just to be clear, who owns + noun?",
    variants: [
      { en: "Just to be clear, who owns the client communication?", ko: "확실히 하자면, 고객과의 소통은 누가 맡죠?" },
      { en: "Just to be clear, who owns the final approval?", ko: "확실히 하자면, 최종 승인은 누가 맡죠?" },
    ],
  },
  {
    no: 46,
    categoryId: "confirming",
    en: "Are we all on the same page here?",
    ko: "다들 여기서 같은 이해를 하고 있나요?",
    verbId: "be",
    pattern: "Are we all on the same page + context?",
    variants: [
      { en: "Are we all on the same page about the revised scope?", ko: "다들 수정된 범위에 대해 같은 생각인가요?" },
      { en: "Are we all on the same page before we proceed?", ko: "진행하기 전에 다들 같은 생각인가요?" },
    ],
  },
  {
    no: 47,
    categoryId: "confirming",
    en: "Does that make sense to everyone?",
    ko: "다들 이해되시나요?",
    verbId: "make",
    pattern: "Does + noun + make sense to everyone?",
    variants: [
      { en: "Does the proposed timeline make sense to everyone?", ko: "제안된 일정이 다들 이해되시나요?" },
      { en: "Does this division of work make sense to everyone?", ko: "이런 업무 분담이 다들 이해되시나요?" },
    ],
  },
  {
    no: 48,
    categoryId: "confirming",
    en: "Correct me if I'm wrong about the date.",
    ko: "날짜가 틀리면 정정해 주세요.",
    verbId: "be",
    pattern: "Correct me if I'm wrong about + noun",
    variants: [
      { en: "Correct me if I'm wrong about the budget figure.", ko: "예산 수치가 틀리면 정정해 주세요." },
      { en: "Correct me if I'm wrong about who is leading the pilot.", ko: "시범 운영 담당자를 제가 잘못 알고 있다면 정정해 주세요." },
    ],
  },
  {
    no: 49,
    categoryId: "suggestions",
    en: "How about we start next Monday?",
    ko: "다음 주 월요일에 시작하는 건 어때요?",
    verbId: null,
    focus: "START",
    pattern: "How about we start + context?",
    variants: [
      { en: "How about we start with a small pilot?", ko: "소규모 시범 운영부터 시작하는 건 어때요?" },
      { en: "How about we start after the holiday?", ko: "연휴 후에 시작하는 건 어때요?" },
    ],
  },
  {
    no: 50,
    categoryId: "suggestions",
    en: "Why don't we split this into two phases?",
    ko: "이걸 두 단계로 나누는 게 어때요?",
    verbId: "do",
    pattern: "Why don't we split + noun + into/by + parts?",
    variants: [
      { en: "Why don't we split the work by region?", ko: "업무를 지역별로 나누는 게 어때요?" },
      { en: "Why don't we split the presentation into three sections?", ko: "발표를 세 부분으로 나누는 게 어때요?" },
    ],
  },
  {
    no: 51,
    categoryId: "suggestions",
    en: "We could try a different vendor.",
    ko: "다른 업체를 시도해 볼 수도 있어요.",
    verbId: null,
    focus: "TRY",
    pattern: "We could try + noun",
    variants: [
      { en: "We could try a local supplier this time.", ko: "이번에는 현지 공급업체를 시도해 볼 수도 있어요." },
      { en: "We could try a different pricing model for the pilot.", ko: "시범 운영에는 다른 가격 체계를 시도해 볼 수도 있어요." },
    ],
  },
  {
    no: 52,
    categoryId: "suggestions",
    en: "What if we push the deadline by a week?",
    ko: "마감을 일주일 미루면 어떨까요?",
    verbId: null,
    focus: "PUSH",
    pattern: "What if we push + noun + by/to + time?",
    variants: [
      { en: "What if we push the launch back by two weeks?", ko: "출시를 2주 미루면 어떨까요?" },
      { en: "What if we push the review deadline to Friday?", ko: "검토 마감을 금요일로 미루면 어떨까요?" },
    ],
  },
  {
    no: 53,
    categoryId: "suggestions",
    en: "I suggest we test it first.",
    ko: "먼저 테스트하는 걸 제안합니다.",
    verbId: null,
    focus: "SUGGEST",
    pattern: "I suggest we test + noun + first",
    variants: [
      { en: "I suggest we test it with one team first.", ko: "먼저 한 팀에서 테스트하는 걸 제안합니다." },
      { en: "I suggest we test the backup process first.", ko: "먼저 백업 절차를 테스트하는 걸 제안합니다." },
    ],
  },
  {
    no: 54,
    categoryId: "suggestions",
    en: "Maybe we should ask the client directly.",
    ko: "아마 고객에게 직접 물어봐야 할 것 같아요.",
    verbId: "ask",
    pattern: "Maybe we should ask + person + question",
    variants: [
      { en: "Maybe we should ask the legal team directly.", ko: "아마 법무팀에 직접 물어봐야 할 것 같아요." },
      { en: "Maybe we should ask users what they actually need.", ko: "아마 사용자에게 실제로 무엇이 필요한지 물어봐야 할 것 같아요." },
    ],
  },
  {
    no: 55,
    categoryId: "suggestions",
    en: "Let's give this idea a try.",
    ko: "이 아이디어를 한번 해보죠.",
    verbId: "give",
    pattern: "Let's give + noun + a try",
    variants: [
      { en: "Let's give the new workflow a try.", ko: "새 업무 절차를 한번 시도해 보죠." },
      { en: "Let's give this vendor another try.", ko: "이 업체에 한 번 더 기회를 줘 보죠." },
    ],
  },
  {
    no: 56,
    categoryId: "delegating",
    en: "Could you send me the report by tomorrow?",
    ko: "내일까지 보고서 보내 주시겠어요?",
    verbId: null,
    focus: "SEND",
    pattern: "Could you send + object + by + time?",
    variants: [
      { en: "Could you send me the final deck by noon?", ko: "정오까지 최종 발표 자료를 보내 주시겠어요?" },
      { en: "Could you send the revised contract to the client today?", ko: "오늘 수정된 계약서를 고객에게 보내 주시겠어요?" },
    ],
  },
  {
    no: 57,
    categoryId: "delegating",
    en: "Can you take care of the follow-up?",
    ko: "후속 처리 맡아 주시겠어요?",
    verbId: "take",
    pattern: "Can you take care of + noun?",
    variants: [
      { en: "Can you take care of the client follow-up?", ko: "고객 후속 연락을 맡아 주시겠어요?" },
      { en: "Can you take care of booking the meeting room?", ko: "회의실 예약을 맡아 주시겠어요?" },
    ],
  },
  {
    no: 58,
    categoryId: "delegating",
    en: "Would you mind sharing your notes?",
    ko: "메모 공유해 주실 수 있을까요?",
    verbId: null,
    focus: "SHARE",
    pattern: "Would you mind sharing + noun?",
    variants: [
      { en: "Would you mind sharing the latest figures?", ko: "최신 수치를 공유해 주실 수 있을까요?" },
      { en: "Would you mind sharing your screen for a moment?", ko: "잠시 화면을 공유해 주실 수 있을까요?" },
    ],
  },
  {
    no: 59,
    categoryId: "delegating",
    en: "Please let me know if anything changes.",
    ko: "뭐라도 바뀌면 알려 주세요.",
    verbId: "let",
    pattern: "Please let me know if + clause",
    variants: [
      { en: "Please let me know if the deadline moves.", ko: "마감일이 바뀌면 알려 주세요." },
      { en: "Please let me know if the client has any concerns.", ko: "고객에게 우려 사항이 있으면 알려 주세요." },
    ],
  },
  {
    no: 60,
    categoryId: "delegating",
    en: "Can you follow up with the team?",
    ko: "팀에 후속 확인해 주시겠어요?",
    verbId: null,
    focus: "FOLLOW UP",
    pattern: "Can you follow up with + person + context?",
    variants: [
      { en: "Can you follow up with finance this afternoon?", ko: "오늘 오후에 재무팀에 후속 확인해 주시겠어요?" },
      { en: "Can you follow up with the vendor about delivery?", ko: "납품 건으로 업체에 후속 확인해 주시겠어요?" },
    ],
  },
  {
    no: 61,
    categoryId: "delegating",
    en: "I'll leave the design part to you.",
    ko: "디자인 부분은 맡길게요.",
    verbId: null,
    focus: "LEAVE TO",
    pattern: "I'll leave + noun + to + person",
    variants: [
      { en: "I'll leave the final layout to you.", ko: "최종 레이아웃은 맡길게요." },
      { en: "I'll leave the client presentation to your team.", ko: "고객 발표는 여러분 팀에 맡길게요." },
    ],
  },
  {
    no: 62,
    categoryId: "delegating",
    en: "Can you keep me posted on the progress?",
    ko: "진행 상황 계속 알려 주시겠어요?",
    verbId: "keep",
    pattern: "Can you keep me posted on + noun?",
    variants: [
      { en: "Can you keep me posted on the approval status?", ko: "승인 상황을 계속 알려 주시겠어요?" },
      { en: "Can you keep me posted while the issue is being resolved?", ko: "문제가 해결되는 동안 계속 상황을 알려 주시겠어요?" },
    ],
  },
  {
    no: 63,
    categoryId: "updates",
    en: "Let me give you a quick update.",
    ko: "간단히 업데이트 드릴게요.",
    verbId: "give",
    pattern: "Let me give you a quick update + context",
    variants: [
      { en: "Let me give you a quick update on the rollout.", ko: "출시에 대해 간단히 업데이트 드릴게요." },
      { en: "Let me give you a quick update before we decide.", ko: "결정하기 전에 간단히 업데이트 드릴게요." },
    ],
  },
  {
    no: 64,
    categoryId: "updates",
    en: "We're right on track with the schedule.",
    ko: "일정대로 잘 가고 있어요.",
    verbId: "be",
    pattern: "We're right on track + context",
    variants: [
      { en: "We're right on track with the product launch.", ko: "제품 출시가 일정대로 잘 진행되고 있어요." },
      { en: "We're right on track to finish by Friday.", ko: "금요일까지 마칠 수 있도록 순조롭게 진행 중이에요." },
    ],
  },
  {
    no: 65,
    categoryId: "updates",
    en: "The design is still in progress.",
    ko: "디자인은 아직 진행 중이에요.",
    verbId: "be",
    pattern: "Noun + is still in progress",
    variants: [
      { en: "The contract review is still in progress.", ko: "계약 검토는 아직 진행 중이에요." },
      { en: "The data migration is still in progress.", ko: "데이터 이전은 아직 진행 중이에요." },
    ],
  },
  {
    no: 66,
    categoryId: "updates",
    en: "We're a bit behind on testing.",
    ko: "테스트가 조금 늦어지고 있어요.",
    verbId: "be",
    pattern: "We're a bit behind on + noun",
    variants: [
      { en: "We're a bit behind on client approvals.", ko: "고객 승인 일정이 조금 늦어지고 있어요." },
      { en: "We're a bit behind on the first milestone.", ko: "첫 번째 주요 일정이 조금 늦어지고 있어요." },
    ],
  },
  {
    no: 67,
    categoryId: "updates",
    en: "We made good progress this week.",
    ko: "이번 주 진전이 좋았어요.",
    verbId: "make",
    pattern: "We made good progress + context",
    variants: [
      { en: "We made good progress on the prototype this week.", ko: "이번 주 프로토타입 작업에 좋은 진전이 있었어요." },
      { en: "We made good progress despite the staffing gap.", ko: "인력 부족에도 불구하고 좋은 진전이 있었어요." },
    ],
  },
  {
    no: 68,
    categoryId: "updates",
    en: "The first phase is almost done.",
    ko: "첫 단계는 거의 끝났어요.",
    verbId: "be",
    pattern: "Noun + is almost done",
    variants: [
      { en: "The contract review is almost done.", ko: "계약 검토는 거의 끝났어요." },
      { en: "The first round of testing is almost done.", ko: "1차 테스트는 거의 끝났어요." },
    ],
  },
  {
    no: 69,
    categoryId: "scheduling",
    en: "We're running out of time today.",
    ko: "오늘 시간이 부족하네요.",
    verbId: "run",
    pattern: "We're running out of time + context",
    variants: [
      { en: "We're running out of time for this discussion.", ko: "이 논의에 쓸 시간이 얼마 남지 않았어요." },
      { en: "We're running out of time before the client call.", ko: "고객 통화 전까지 시간이 얼마 남지 않았어요." },
    ],
  },
  {
    no: 70,
    categoryId: "scheduling",
    en: "Let's keep this part short.",
    ko: "이 부분은 짧게 하죠.",
    verbId: "keep",
    pattern: "Let's keep + noun + short",
    variants: [
      { en: "Let's keep the status update short.", ko: "진행 상황 업데이트는 짧게 하죠." },
      { en: "Let's keep the client discussion short.", ko: "고객 관련 논의는 짧게 하죠." },
    ],
  },
  {
    no: 71,
    categoryId: "scheduling",
    en: "Can we take this offline after the meeting?",
    ko: "이건 회의 후 따로 얘기할까요?",
    verbId: "take",
    pattern: "Can we take + noun + offline + context?",
    variants: [
      { en: "Can we take the budget discussion offline after this call?", ko: "예산 논의는 이 통화 후 따로 할까요?" },
      { en: "Can we take the technical questions offline with the engineers?", ko: "기술 관련 질문은 엔지니어들과 따로 논의할까요?" },
    ],
  },
  {
    no: 72,
    categoryId: "scheduling",
    en: "Let's set a deadline for this.",
    ko: "이것에 대한 마감을 정하죠.",
    verbId: null,
    focus: "SET",
    pattern: "Let's set a deadline for + noun",
    variants: [
      { en: "Let's set a firm deadline for the first draft.", ko: "1차 초안의 명확한 마감일을 정하죠." },
      { en: "Let's set a review deadline before we leave.", ko: "마치기 전에 검토 마감을 정하죠." },
    ],
  },
  {
    no: 73,
    categoryId: "scheduling",
    en: "When can you get this done by?",
    ko: "이거 언제까지 되나요?",
    verbId: "get",
    pattern: "When can + person + get + noun + done by?",
    variants: [
      { en: "When can you get the revised proposal done by?", ko: "수정 제안서는 언제까지 완료할 수 있나요?" },
      { en: "When can your team get the testing done by?", ko: "팀에서 테스트를 언제까지 끝낼 수 있나요?" },
    ],
  },
  {
    no: 74,
    categoryId: "scheduling",
    en: "Let's schedule a follow-up for next week.",
    ko: "다음 주에 후속 미팅을 잡죠.",
    verbId: null,
    focus: "SCHEDULE",
    pattern: "Let's schedule a follow-up + time",
    variants: [
      { en: "Let's schedule a follow-up for Thursday afternoon.", ko: "목요일 오후에 후속 미팅을 잡죠." },
      { en: "Let's schedule a follow-up once the data is ready.", ko: "데이터가 준비되면 후속 미팅을 잡죠." },
    ],
  },
  {
    no: 75,
    categoryId: "turn-taking",
    en: "Can I jump in here for a second?",
    ko: "잠깐 끼어들어도 될까요?",
    verbId: null,
    focus: "JUMP IN",
    pattern: "Can I jump in + context?",
    variants: [
      { en: "Can I jump in here with one concern?", ko: "우려되는 점 하나 말씀드리려고 잠깐 끼어들어도 될까요?" },
      { en: "Can I jump in for a quick clarification?", ko: "간단히 확인하려고 잠깐 끼어들어도 될까요?" },
    ],
  },
  {
    no: 76,
    categoryId: "turn-taking",
    en: "Sorry to interrupt, but I have a question.",
    ko: "끼어들어서 죄송한데 질문이 있어요.",
    verbId: "have",
    pattern: "Sorry to interrupt, but I have + noun",
    variants: [
      { en: "Sorry to interrupt, but I have an update.", ko: "끼어들어서 죄송한데 업데이트가 있어요." },
      { en: "Sorry to interrupt, but I have a different figure.", ko: "끼어들어서 죄송한데 제가 가진 수치가 달라요." },
    ],
  },
  {
    no: 77,
    categoryId: "turn-taking",
    en: "Go ahead, please finish your point.",
    ko: "말씀하세요, 계속하세요.",
    verbId: "go",
    pattern: "Go ahead, please finish + noun",
    variants: [
      { en: "Go ahead, please finish your explanation.", ko: "말씀하세요, 설명을 마저 해 주세요." },
      { en: "Go ahead, please finish what you were saying.", ko: "말씀하세요, 하시던 말씀을 마저 해 주세요." },
    ],
  },
  {
    no: 78,
    categoryId: "turn-taking",
    en: "Please continue, I didn't mean to cut you off.",
    ko: "계속하세요, 끊을 의도는 아니었어요.",
    verbId: "mean",
    pattern: "Please continue, I didn't mean to + verb",
    variants: [
      { en: "Please continue, I didn't mean to interrupt your summary.", ko: "계속하세요, 요약을 끊을 의도는 아니었어요." },
      { en: "Please continue, I didn't mean to speak over you.", ko: "계속하세요, 말씀 중에 겹쳐 말할 의도는 아니었어요." },
    ],
  },
  {
    no: 79,
    categoryId: "turn-taking",
    en: "One more thing before we move on.",
    ko: "넘어가기 전에 하나 더요.",
    verbId: null,
    focus: "MOVE ON",
    pattern: "One more thing before we + verb",
    variants: [
      { en: "One more thing before we discuss the budget.", ko: "예산을 논의하기 전에 하나 더요." },
      { en: "One more thing before we close this topic.", ko: "이 주제를 마무리하기 전에 하나 더요." },
    ],
  },
  {
    no: 80,
    categoryId: "wrapping-up",
    en: "Let's wrap up the meeting here.",
    ko: "회의는 여기서 마무리하죠.",
    verbId: null,
    focus: "WRAP UP",
    pattern: "Let's wrap up + noun + context",
    variants: [
      { en: "Let's wrap up the meeting in the next five minutes.", ko: "앞으로 5분 안에 회의를 마무리하죠." },
      { en: "Let's wrap up here and confirm the action items.", ko: "여기서 마무리하고 실행 항목을 확인하죠." },
    ],
  },
  {
    no: 81,
    categoryId: "wrapping-up",
    en: "To sum up, we agreed on three points.",
    ko: "요약하자면 세 가지에 합의했어요.",
    verbId: null,
    focus: "SUM UP",
    pattern: "To sum up, we agreed on + noun",
    variants: [
      { en: "To sum up, we agreed on the launch date and budget.", ko: "요약하자면 출시일과 예산에 합의했어요." },
      { en: "To sum up, we agreed on the scope but not the timeline.", ko: "요약하자면 범위에는 합의했지만 일정에는 합의하지 못했어요." },
    ],
  },
  {
    no: 82,
    categoryId: "wrapping-up",
    en: "So, to recap what we discussed today...",
    ko: "그럼 오늘 논의한 걸 정리하자면...",
    verbId: null,
    focus: "RECAP",
    pattern: "So, to recap what + clause...",
    variants: [
      { en: "So, to recap what we decided this morning...", ko: "그럼 오늘 아침 결정한 걸 정리하자면..." },
      { en: "So, to recap what each team needs to do...", ko: "그럼 각 팀이 해야 할 일을 정리하자면..." },
    ],
  },
  {
    no: 83,
    categoryId: "wrapping-up",
    en: "That's all for today, thank you.",
    ko: "오늘은 여기까지입니다, 감사합니다.",
    verbId: "be",
    pattern: "That's all for + noun, thank you",
    variants: [
      { en: "That's all for this session, thank you.", ko: "이번 회의는 여기까지입니다, 감사합니다." },
      { en: "That's all for today's review. Thank you for the input.", ko: "오늘 검토는 여기까지입니다. 의견 주셔서 감사합니다." },
    ],
  },
  {
    no: 84,
    categoryId: "wrapping-up",
    en: "Any final thoughts before we close?",
    ko: "마치기 전에 마지막으로 하실 말씀 있나요?",
    verbId: null,
    focus: "CLOSE",
    pattern: "Any final thoughts + context?",
    variants: [
      { en: "Any final thoughts before we end the call?", ko: "통화를 마치기 전에 마지막으로 하실 말씀 있나요?" },
      { en: "Any final thoughts on the proposal before we close?", ko: "마치기 전에 제안서에 대해 마지막으로 하실 말씀 있나요?" },
    ],
  },
  {
    no: 85,
    categoryId: "wrapping-up",
    en: "Let's call it a day, good work everyone.",
    ko: "오늘은 이만하죠, 다들 수고했어요.",
    verbId: "call",
    pattern: "Let's call it a day + context",
    variants: [
      { en: "Let's call it a day and pick this up tomorrow.", ko: "오늘은 이만하고 내일 이어서 하죠." },
      { en: "Let's call it a day, great work on the proposal.", ko: "오늘은 이만하죠, 제안서 작업 수고 많으셨어요." },
    ],
  },
  {
    no: 86,
    categoryId: "follow-up",
    en: "Let's follow up on this next week.",
    ko: "이건 다음 주에 다시 챙기죠.",
    verbId: null,
    focus: "FOLLOW UP",
    pattern: "Let's follow up + time/context",
    variants: [
      { en: "Let's follow up on the open questions next Tuesday.", ko: "남은 질문은 다음 주 화요일에 다시 챙기죠." },
      { en: "Let's follow up once the client responds.", ko: "고객이 답변하면 다시 챙기죠." },
    ],
  },
  {
    no: 87,
    categoryId: "follow-up",
    en: "I'll send out the meeting minutes today.",
    ko: "오늘 회의록 보낼게요.",
    verbId: null,
    focus: "SEND OUT",
    pattern: "I'll send out + noun + time",
    variants: [
      { en: "I'll send out the action-item summary this afternoon.", ko: "오늘 오후에 실행 항목 요약을 보낼게요." },
      { en: "I'll send out the revised meeting minutes by noon.", ko: "정오까지 수정된 회의록을 보낼게요." },
    ],
  },
  {
    no: 88,
    categoryId: "follow-up",
    en: "Who's taking this action item?",
    ko: "이 실행 항목은 누가 맡죠?",
    verbId: "take",
    pattern: "Who's taking + noun?",
    variants: [
      { en: "Who's taking the action item for client follow-up?", ko: "고객 후속 연락 실행 항목은 누가 맡죠?" },
      { en: "Who's taking ownership of the budget analysis?", ko: "예산 분석은 누가 맡죠?" },
    ],
  },
  {
    no: 89,
    categoryId: "follow-up",
    en: "Let's assign owners to each task.",
    ko: "각 업무에 담당자를 정하죠.",
    verbId: null,
    focus: "ASSIGN",
    pattern: "Let's assign + owner + to + task",
    variants: [
      { en: "Let's assign one owner to each workstream.", ko: "각 업무 흐름에 담당자 한 명씩 정하죠." },
      { en: "Let's assign clear owners before we finish.", ko: "마치기 전에 담당자를 명확히 정하죠." },
    ],
  },
  {
    no: 90,
    categoryId: "follow-up",
    en: "I'll get back to you by end of day.",
    ko: "오늘 안에 다시 연락드릴게요.",
    verbId: "get",
    pattern: "I'll get back to + person + by/after + time",
    variants: [
      { en: "I'll get back to you with the numbers by noon.", ko: "정오까지 수치를 확인해 다시 연락드릴게요." },
      { en: "I'll get back to the team after I speak with legal.", ko: "법무팀과 이야기한 후 팀에 다시 연락할게요." },
    ],
  },
  {
    no: 91,
    categoryId: "small-talk",
    en: "How's everything going with you?",
    ko: "요즘 어떻게 지내세요?",
    verbId: "go",
    pattern: "How's everything going with + noun?",
    variants: [
      { en: "How's everything going with the new project?", ko: "새 프로젝트는 어떻게 진행되고 있어요?" },
      { en: "How's everything going with your new team?", ko: "새 팀에서는 어떻게 지내세요?" },
    ],
  },
  {
    no: 92,
    categoryId: "small-talk",
    en: "How was your weekend?",
    ko: "주말 잘 보내셨어요?",
    verbId: "be",
    pattern: "How was + noun?",
    variants: [
      { en: "How was your trip last week?", ko: "지난주 출장 어떠셨어요?" },
      { en: "How was your first week in the new role?", ko: "새 역할에서 보낸 첫 주는 어떠셨어요?" },
    ],
  },
  {
    no: 93,
    categoryId: "small-talk",
    en: "It's good to see you all again.",
    ko: "다시 뵈어서 반가워요.",
    verbId: "see",
    pattern: "It's good to see + person + again",
    variants: [
      { en: "It's good to see you all in person again.", ko: "다시 직접 뵈어서 반가워요." },
      { en: "It's good to see the regional teams together again.", ko: "지역 팀들이 다시 함께한 모습을 보니 반가워요." },
    ],
  },
  {
    no: 94,
    categoryId: "small-talk",
    en: "Thanks, everyone, for your time.",
    ko: "다들 시간 내주셔서 감사합니다.",
    verbId: null,
    focus: "THANKS FOR",
    pattern: "Thanks, everyone, for + noun/-ing",
    variants: [
      { en: "Thanks, everyone, for your thoughtful feedback.", ko: "다들 세심한 피드백 주셔서 감사합니다." },
      { en: "Thanks, everyone, for staying a little longer.", ko: "다들 조금 더 남아 주셔서 감사합니다." },
    ],
  },
  {
    no: 95,
    categoryId: "small-talk",
    en: "Let's keep in touch on this.",
    ko: "이 건 계속 연락해요.",
    verbId: "keep",
    pattern: "Let's keep in touch + context",
    variants: [
      { en: "Let's keep in touch as the rollout progresses.", ko: "출시가 진행되는 동안 계속 연락해요." },
      { en: "Let's keep in touch about the partnership opportunity.", ko: "협력 기회에 대해 계속 연락해요." },
    ],
  },
  {
    no: 96,
    categoryId: "virtual",
    en: "Can you hear me clearly now?",
    ko: "이제 제 말 잘 들리세요?",
    verbId: null,
    focus: "HEAR",
    pattern: "Can you hear me clearly + context?",
    variants: [
      { en: "Can you hear me clearly after I switched devices?", ko: "기기를 바꾼 뒤에는 제 말이 잘 들리세요?" },
      { en: "Can you hear me clearly without the headset?", ko: "헤드셋 없이도 제 말 잘 들리세요?" },
    ],
  },
  {
    no: 97,
    categoryId: "virtual",
    en: "I think you're on mute.",
    ko: "음소거 되신 것 같아요.",
    verbId: "think",
    pattern: "I think + person + is on mute",
    variants: [
      { en: "I think you're still on mute.", ko: "아직 음소거 상태이신 것 같아요." },
      { en: "I think your microphone is muted again.", ko: "마이크가 다시 음소거된 것 같아요." },
    ],
  },
  {
    no: 98,
    categoryId: "virtual",
    en: "Let me share my screen now.",
    ko: "지금 화면 공유할게요.",
    verbId: "let",
    pattern: "Let me share + noun + now",
    variants: [
      { en: "Let me share my screen and pull up the latest dashboard.", ko: "화면을 공유해서 최신 대시보드를 띄울게요." },
      { en: "Let me share my screen so you can see the figures.", ko: "수치를 보실 수 있게 화면을 공유할게요." },
    ],
  },
  {
    no: 99,
    categoryId: "virtual",
    en: "Can everyone see my screen?",
    ko: "다들 화면 보이세요?",
    verbId: "see",
    pattern: "Can everyone see + noun?",
    variants: [
      { en: "Can everyone see the full slide deck on my screen?", ko: "다들 제 화면의 전체 발표 자료가 보이세요?" },
      { en: "Can everyone see the chart I just opened?", ko: "다들 방금 연 차트가 보이세요?" },
    ],
  },
  {
    no: 100,
    categoryId: "virtual",
    en: "Sorry, you're breaking up a little.",
    ko: "죄송한데 소리가 좀 끊겨요.",
    verbId: "break",
    pattern: "Sorry, + person/audio + is breaking up",
    variants: [
      { en: "Sorry, your audio keeps breaking up on my end.", ko: "죄송한데 제 쪽에서 음성이 계속 끊겨요." },
      { en: "Sorry, you're breaking up whenever you speak.", ko: "죄송한데 말씀하실 때마다 소리가 끊겨요." },
    ],
  },
];

const categoryById = Object.fromEntries(
  meetingCategories.map((category) => [category.id, category]),
);

const meetingId = (no) => `meeting-${String(no).padStart(3, "0")}`;

export const meetingSentences = sentenceRows.map((sentence) => {
  const category = categoryById[sentence.categoryId];
  const id = meetingId(sentence.no);
  const focus = sentence.focus ?? (sentence.verbId ? sentence.verbId.toUpperCase() : "MEETING");

  return {
    id,
    no: sentence.no,
    categoryId: sentence.categoryId,
    categoryKo: category.ko,
    categoryEn: category.en,
    en: sentence.en,
    ko: sentence.ko,
    verbId: sentence.verbId,
    focus,
    pattern: sentence.pattern,
    variants: sentence.variants.map((variant, index) => ({
      id: `${id}-v${index + 1}`,
      en: variant.en,
      ko: variant.ko,
    })),
  };
});

export const meetingPracticeCards = meetingSentences.flatMap((sentence) => {
  const shared = {
    verbId: sentence.verbId,
    verb: sentence.focus,
    hint: sentence.pattern,
    meaning: `${sentence.categoryKo} 상황에서 '${sentence.pattern}' 틀로 말하기`,
    context: sentence.categoryKo,
    meetingNo: sentence.no,
  };

  return [
    {
      id: `${sentence.id}-original`,
      ...shared,
      ko: sentence.ko,
      answer: sentence.en,
      kind: "original",
    },
    ...sentence.variants.map((variant) => ({
      id: variant.id,
      ...shared,
      ko: variant.ko,
      answer: variant.en,
      kind: "application",
    })),
  ];
});

const studyDays = Array.from({ length: 25 }, (_, index) => {
  const day = index + 1;
  const firstNo = index * 4 + 1;
  const lastNo = firstNo + 3;
  const sentences = meetingSentences.slice(firstNo - 1, lastNo);
  const focus = [...new Set(sentences.map((sentence) => sentence.categoryKo))].join(" / ");

  return {
    day,
    title: `Meeting sentences ${firstNo}-${lastNo}`,
    focus,
    sentenceIds: sentences.map((sentence) => sentence.id),
    review: false,
  };
});

const reviewDays = Array.from({ length: 5 }, (_, index) => ({
  day: index + 26,
  title: `Spaced review ${index + 1}`,
  focus: "Interleaved review across all meeting categories",
  sentenceIds: Array.from({ length: 20 }, (_, itemIndex) =>
    meetingId(index + 1 + itemIndex * 5),
  ),
  review: true,
}));

export const meetingMonthPlan = [...studyDays, ...reviewDays];
